dir: "mocks"
structname: "{{.InterfaceName}}"
pkgname:  "mocks"
filename: "{{.InterfaceName}}.go"
packages:
  github.com/acidspud/coding-challange/repository/redis:
    interfaces:
      RedisRepository:
  github.com/acidspud/coding-challange/domain:
    interfaces:
      UserRepository:
      ItemRepository:
      AuthUsecase:
      ItemUsecase:
  github.com/acidspud/coding-challange/utils:
    interfaces:
      HttpErr:
  github.com/acidspud/coding-challange/utils/jwt:
    interfaces:
      JWTService:
  github.com/acidspud/coding-challange/utils/crypto:
    interfaces:
      CryptoService:
