export const LOGGED_IN_USER = 'LOGGED_IN_USER'
export const LOGOUT = 'LOGOUT'
export const FETCH_ITEM_LIST = 'FETCH_ITEM_LIST'
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
