// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/acidspud/gotbot-coding-challange/domain"

	request "github.com/acidspud/gotbot-coding-challange/transport/request"
)

// ItemUsecase is an autogenerated mock type for the ItemUsecase type
type ItemUsecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, _a1
func (_m *ItemUsecase) Create(ctx context.Context, _a1 *request.CreateItemReq) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *request.CreateItemReq) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ItemUsecase) Delete(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Fetch provides a mock function with given fields: ctx
func (_m *ItemUsecase) Fetch(ctx context.Context) ([]domain.Item, error) {
	ret := _m.Called(ctx)

	var r0 []domain.Item
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Item); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ItemUsecase) GetByID(ctx context.Context, id int64) (domain.Item, error) {
	ret := _m.Called(ctx, id)

	var r0 domain.Item
	if rf, ok := ret.Get(0).(func(context.Context, int64) domain.Item); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Item)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, _a2
func (_m *ItemUsecase) Update(ctx context.Context, id int64, _a2 *request.UpdateItemReq) error {
	ret := _m.Called(ctx, id, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, *request.UpdateItemReq) error); ok {
		r0 = rf(ctx, id, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewItemUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewItemUsecase creates a new instance of ItemUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewItemUsecase(t mockConstructorTestingTNewItemUsecase) *ItemUsecase {
	mock := &ItemUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
